In [23]:
import torch
import numpy as np

In [5]:
# torch shape 생성 후 정보 출력
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)
print(t1.device)
print(t1.requires_grad)
print(t1.size())
print(t1.shape)

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [10]:
a1 = torch.tensor(1)
a2 = torch.tensor([1])

print(a1.shape, a1.ndim) # 0차원
print(a2.shape, a2.ndim) # 1차원

torch.Size([]) 0
torch.Size([1]) 1


In [12]:
a3 = torch.tensor([1, 2, 3, 4, 5]) # 1차원
a4 = torch.tensor([[1], [2], [3], [4], [5]]) # 2차원
print(a3.shape, a3.ndim)
print(a4.shape, a4.ndim)

torch.Size([5]) 1
torch.Size([5, 1]) 2


In [13]:
a5 = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim) # 2차원

torch.Size([3, 2]) 2


In [14]:
a6 = torch.tensor([
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim) # 3차원

torch.Size([3, 2, 1]) 3


In [15]:
a7 = torch.tensor([
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim) # 4차원

torch.Size([3, 1, 2, 1]) 4


In [16]:
a8 = torch.tensor([
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim) # 4차원

torch.Size([3, 1, 2, 3]) 4


In [17]:
a9 = torch.tensor([
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim) # 5차원

torch.Size([3, 1, 2, 3, 1]) 5


In [18]:
a10 = torch.tensor([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim) # 2차원

torch.Size([4, 5]) 2


In [20]:
a10 = torch.tensor([
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim) # 3차원

torch.Size([4, 1, 5]) 3


In [22]:
# 에러발생 valueError: tensor shape에서 같은 차원의 원소 수는 같아야 한다
a11 = torch.tensor([
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

ValueError: expected sequence of length 3 at dim 3 (got 2)

In [29]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1) # Tensor (대문자)

l2 = [1, 2, 3]
t2 = torch.tensor(l2) # tensor (소문자)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3) # as_tensor

# 모두 [0] 값이 1이다.
l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [31]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

# l6만 [0]값이 100 이다.
l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


In [34]:
# 두 개의 차이점을 모르겠다. 복사의 의미인 것 같다.
t1 = torch.ones(size=(5,))
t1_like = torch.ones_like(input=t1)
print(t1)
print(t1_like)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [37]:
# 어떨 때 사용하는 함수인지 알고 싶다. 의미는 대충 유추 가능하다.
t2 = torch.zeros(size=(6,))
t2_like = torch.zeros_like(input=t2)
print(t2)
print(t2_like)

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [39]:
# 이것도 어떨 때 사용하는 함수인지 모르겠다.
t3 = torch.empty(size=(4,))
t3_like = torch.empty_like(input=t3)
print(t3)
print(t3_like)

tensor([0., 0., 0., 0.])
tensor([0., 0., 0., 0.])


In [40]:
# 이것도 마찬가지로 이런 함수들이 사용되는 실코드를 보면 좀 더 와 닿을 것 같다.
t4 = torch.eye(n=3)
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [43]:
# shape에 맞는 원소를 10 ~ 20 랜덤하게 추출한다.
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

tensor([[19, 14]])


In [48]:
# 여러 번 돌려본 결과 0 ~ 1 사이의 값에서 랜덤하게 추출하는 것 같다.
t2 = torch.rand(size=(1, 3))
print(t2)

tensor([[0.3441, 0.3174, 0.9719]])


In [56]:
# 평균이 0 이고, 표준편차가 1인 정규분포에서 랜덤 추출
t3 = torch.randn(size=(1, 3))
print(t3)

tensor([[-0.0752, -2.5310,  1.5608]])


In [57]:
# 평균이 10, 표준편차가 1인 정규분포에서 랜덤 추출
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

tensor([[11.4024,  9.1320],
        [10.5178,  9.9780],
        [ 9.9669,  8.4495]])


In [58]:
# 0 ~ 5 까지의 숫자를 3등분
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

tensor([0.0000, 2.5000, 5.0000])


In [60]:
t6 = torch.arange(5)
print(t6)

tensor([0, 1, 2, 3, 4])


In [101]:
# seed를 줌으로써 난수 추출임에도 계속 같은 결과가 나온다
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [83]:
# seed가 없는 랜덤 값 추출이다.
random2 = torch.rand(2, 3)
print(random2)

tensor([[0.5062, 0.8469, 0.2588],
        [0.2707, 0.4115, 0.6839]])


In [100]:
# 아무리 실행해도 계속 같은 값이 나온다
torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [104]:
# 요소의 타입 지정과 배수
a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[11.2406, 11.2083, 11.6692],
        [18.3283,  0.2118, 18.4972]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [106]:
# 전부 요소의 타입을 지정해준다
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)
print(double_d.dtype)
print(short_e.dtype)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()
print(double_d.dtype)
print(short_e.dtype)

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)
print(double_d.dtype)
print(short_e.dtype)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)
print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16
torch.float64
torch.int16
torch.float64
torch.int16
torch.float64
torch.int16


In [107]:
# double과 short이 곱해지면 float64 타입이다
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float64


In [109]:
# shape의 덧셈: 각각의 요소 값이 더해진다.
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [110]:
# shape의 뺄셈: 각각의 요소 값이 빼진다.
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [111]:
# shape의 곱셈: 각각의 요소 값이 곱해진다.
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [112]:
# shape의 나눗셈: 각각의 요소 값이 나눠진다.
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [113]:
# 두 텐서의 도트 곱을 계산하는 데 사용되는 함수
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

tensor(7) torch.Size([])


In [115]:
# matrix multiplication을 수행하는 함수.
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t2)
print(t3)
print(t4, t4.size())

tensor([[ 1.4798, -0.9832,  0.2359],
        [ 0.7787, -0.1732, -0.1074]])
tensor([[1.9456, 0.4525],
        [0.1014, 0.3339],
        [1.6279, 1.0423]])
tensor([[3.1635, 0.5872],
        [1.3227, 0.1826]]) torch.Size([2, 2])


In [116]:
# 배치 행렬의 곱을 수행하는 함수.
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())

torch.Size([10, 3, 5])


In [121]:
# 다 차원 텐서의 곱.
t1 = torch.randn(3)
t2 = torch.randn(3)
print(t1)
print(t2)
print(torch.matmul(t1, t2)) 
print(torch.matmul(t1, t2).size())  # torch.Size([])

tensor([-0.2213, -0.9576,  0.6160])
tensor([-0.2437, -1.0848, -0.1134])
tensor(1.0229)
torch.Size([])


In [124]:
# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(t3)
print(t4)
print(torch.matmul(t3, t4))
print(torch.matmul(t3, t4).size())  # torch.Size([3])

tensor([[ 1.3087,  0.5022, -0.6916, -0.8422],
        [ 0.2753,  1.2003, -0.9799,  0.2312],
        [ 0.3935, -1.0526,  0.0445,  0.4836]])
tensor([-2.2901,  0.2022,  0.8739, -0.7298])
tensor([-2.8854, -1.4129, -1.4280])
torch.Size([3])


In [126]:
# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(t5)
print(t6)
print(torch.matmul(t5, t6))
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

tensor([[[ 1.2991,  0.6876,  0.1600, -0.1573],
         [-0.1636,  2.2726, -0.6044, -0.7800],
         [-0.7321, -0.9691,  0.1006,  1.2635]],

        [[-1.1083,  1.6996,  0.1919,  1.1183],
         [ 0.6541, -0.0252,  0.1487,  0.8555],
         [-1.1919, -0.1679, -0.4703,  0.6281]],

        [[-0.8714, -2.7357, -0.2126,  2.7737],
         [ 0.1955,  0.8302, -0.0268, -0.8900],
         [ 0.1850, -0.8115,  1.4975,  1.0828]],

        [[-0.3718,  0.5212, -0.0692, -0.3335],
         [-0.9142, -1.5745, -0.9182,  0.1102],
         [-0.1746,  0.6426, -0.0864,  0.2053]],

        [[-0.2020, -1.8797,  0.4979, -0.0546],
         [ 0.1969, -0.2241, -1.7072, -0.9440],
         [ 1.5253, -0.2800, -0.0539,  1.0620]],

        [[ 0.0960,  0.5090, -0.7409, -0.1803],
         [ 1.6447, -0.0988, -0.2642, -1.0275],
         [-0.8639, -1.0955,  0.5540,  0.8996]],

        [[-0.2836, -0.4117, -1.3786,  0.2054],
         [-0.9495,  1.7504, -0.3972, -0.9522],
         [-0.1137, -1.1088, -1.5844, -0.6912]],


In [127]:
# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

torch.Size([10, 3, 5])


In [128]:
# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])

torch.Size([10, 3, 5])


In [129]:
# 각 요소에 상수를 곱한다
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

tensor([2., 4., 6.])


In [130]:
# 텐서의 뺄셈
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [131]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [133]:
# 함수 선언.
def normalize(x):
  return x / 255

t6 = torch.randn(3, 28, 28)
print(t6)
# size가 변하지 않는다
print(normalize(t6).size())

tensor([[[-0.0521,  1.1012,  0.1582,  ..., -0.1844, -2.0253,  1.3944],
         [ 0.8820, -0.2524, -0.8701,  ..., -0.0858,  0.5721, -1.4943],
         [-1.4274, -3.5141,  0.1645,  ...,  0.2156, -0.2704,  0.8386],
         ...,
         [-0.5019,  1.0391, -1.3773,  ...,  0.2726,  2.1886, -0.7139],
         [-1.5227, -2.4398,  0.3726,  ...,  0.3698, -1.2019, -0.4324],
         [-0.5458, -1.2862,  0.9492,  ..., -2.1698, -0.4635, -0.6736]],

        [[-0.7413, -0.7199,  0.3351,  ..., -0.9433, -1.6693,  0.1192],
         [-0.6037,  0.2190, -1.6042,  ...,  2.2884,  0.7299, -0.8898],
         [ 0.3499,  2.2202, -0.7354,  ...,  0.2103, -0.1335, -0.3143],
         ...,
         [ 0.6142, -0.3018,  1.0158,  ...,  0.2178, -1.6243,  0.3438],
         [-0.9023,  1.6379,  0.1072,  ...,  0.1798,  1.0705, -1.0282],
         [-0.4585,  0.6231, -0.5738,  ..., -0.7989, -0.2944, -0.5745]],

        [[ 1.1993, -1.0620,  1.2686,  ...,  0.2856, -0.1421, -0.8956],
         [-0.5984,  0.2588,  0.0406,  ...,  1

In [134]:
# 각 tensor의 shape별 덧셈 방법
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [135]:
# 다른 shape의 곱셈
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

torch.Size([4, 3, 2])


In [136]:
t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

torch.Size([4, 3, 2])


In [137]:
t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

torch.Size([4, 3, 2])


In [138]:
t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

torch.Size([5, 3, 4, 1])


In [139]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

torch.Size([5, 3, 4, 1])


In [140]:
t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

torch.Size([3, 1, 7])


In [141]:
t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

torch.Size([3, 3, 3])


In [142]:
t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

tensor([5., 5., 5., 5.])


In [143]:
# 제곱
t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

tensor([25., 25., 25., 25.])


In [144]:
exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

tensor([  1.,   4.,  27., 256.])


In [147]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

# 텐서 슬라이싱 결과
print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [150]:
y = torch.zeros((6, 6))
# 텐서 값 변경
y[1:4, 2] = 1
print(y)

# 텐서 값 슬라이싱
print(y[1:4, 1:4])

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [152]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
# 텐서 값 슬라이싱 및 변경
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


In [154]:
# shape의 모양을 바꿔준다
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])


In [155]:
t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [157]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t6)
print(t7)
print(t8)

tensor([[[1],
         [2],
         [3]]])
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [160]:
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])
print(t9)

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
print(t11)

t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [161]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

tensor([1, 2, 3, 4, 5, 6])


In [162]:
# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [163]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
#차원 교환 함수.
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [166]:
# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [167]:
# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [169]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

print(t1)
# 텐서 합치기
t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

tensor([[[0., 0., 0.]],

        [[0., 0., 0.]]])
torch.Size([2, 6, 3])


In [170]:
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

# 텐서 합치기
t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [171]:
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [172]:
t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)

torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [174]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [177]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


In [180]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
print(t1.unsqueeze(dim=0))
print(t1.unsqueeze(dim=0).shape)
print(t2.unsqueeze(dim=0))
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

tensor([[[1, 2, 3],
         [4, 5, 6]]])
torch.Size([1, 2, 3])
tensor([[[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3]) True


In [181]:
# stack은 차원을 하나 더 새로 만들어서 합친다.
t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

torch.Size([2, 2, 3]) True


In [182]:
t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 3, 2]) True


In [185]:
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True


In [191]:
print(t9.shape, t10.shape)
t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))

torch.Size([3]) torch.Size([3])
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


In [193]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
print(t1.shape, t2.shape)

# 두 개의 텐서를 위-아래로 합치기
t3 = torch.vstack((t1, t2))
print(t3)
print(t3.shape)

torch.Size([3]) torch.Size([3])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [195]:
t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
# 두 개의 텐서를 위-아래로 합치기
t6 = torch.vstack((t4, t5))
print(t4.shape, t5.shape)
print(t6.shape)
print(t6)

torch.Size([3, 1]) torch.Size([3, 1])
torch.Size([6, 1])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [197]:
t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

# 두 개의 텐서를 위-아래로 합치기
t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [199]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t10.shape, t11.shape)
print(t12.shape)
print(t12)
# cat과 비슷하다.

torch.Size([3]) torch.Size([3])
torch.Size([6])
tensor([1, 2, 3, 4, 5, 6])


In [201]:
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])

# 두 개의 텐서를 좌-우로 합치기
t15 = torch.hstack((t13, t14))
print(t13.shape, t14.shape)
print(t15.shape)
print(t15)

torch.Size([3, 1]) torch.Size([3, 1])
torch.Size([3, 2])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [202]:
t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

# 두 개의 텐서를 좌-우로 합치기
t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


코딩을 통한 고찰
-> 이번 과제는 tensor의 기본 문법들을 익힐 수 있었다. 원래 파이썬의 문법을 알고 있어서 코드를 읽는데에는 어려움이 없었으나, tensor만의 차원 계산이 익숙하지 않았는데 이번 과제를 통하여 좀 더 유연하게 다룰 수 있게 되었다.

숙제 후기
-> 과제의 예제 양이 너무 많았다. 익숙해지는 데에 도움이 되긴 했지만, 오히려 적은 예제로 생각할 시간을 많이 갖게 하는 것이 좋을 것 같다. 그리고 이 기초 문법의 함수들만 나열 식으로 사용하다 보니 함수들이 잘 와닿지 않았다. 실생활 코드 속에 녹아 있는 예제였으면 더 좋았을 것이다.